name: Prettier

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - '.github/**'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{md}
          only_changed: True
          commit_message: "style: prettify code"
          working_directory: docs/
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}